# ##THIS FILE IS READ-ONLY. To update project dependencies, use the 'oyda fetch' command in your terminal. ###
name: people_app
description: A new Oyda project.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  oydadb: ^1.0.8
  validators: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
